# Generated by Django 4.2.7 on 2023-11-18 18:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(default='797405', max_length=6)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 18, 18, 18, 8, 378739, tzinfo=datetime.timezone.utc))),
                ('use_before', models.DateTimeField(default=datetime.datetime(2023, 11, 18, 18, 18, 8, 378739, tzinfo=datetime.timezone.utc))),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
