# Generated by Django 4.2.7 on 2023-11-20 04:06

from django.db import migrations, models
import pin_code_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_code_app', '0002_alter_record_created_at_alter_record_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(default=pin_code_app.models.default_date),
        ),
        migrations.AlterField(
            model_name='record',
            name='use_before',
            field=models.DateTimeField(default=pin_code_app.models.default_date_plus_five_min),
        ),
    ]
