# Generated by Django 4.2.7 on 2023-11-18 18:19

from django.db import migrations, models
import django.utils.timezone
import pin_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='record',
            name='pin_code',
            field=models.CharField(default=pin_app.models.default_pin_code, max_length=6),
        ),
        migrations.AlterField(
            model_name='record',
            name='use_before',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
